### ISSUE TITLE
Style Rubric directive

### ISSUE THREAD

**Issue by KevinCathcart** [readthedocs/sphinx_rtd_theme#116]
The rubric directive is not currently styled. The sphinx basic stylesheet styles it as:

``` css
p.rubric {
    margin-top: 30px;
    font-weight: bold;
}
```

At the moment I'm working around this by adding the following to a suplimentary stylesheet:

``` css
p.rubric {
margin-bottom: 12px; /* about the same size as an H6 margin (i.e. .83 em) */
font-weight: bold;
}
```
