### ISSUE TITLE
Wide table handling is not flexible, how to override the CSS?

### ISSUE THREAD

**Issue by smartass101** [readthedocs/sphinx_rtd_theme#117]
I understand that wide tables need special handling in responsive designs.
However, on a computer screen a table like this http://docs.getpelican.com/en/latest/settings.html#basic-settings is very inconvenient to read.

Any ideas how to address this inconvenience?
I tried to override the CSS style for the table as described in https://github.com/getpelican/pelican/issues/1311 (specifically commit https://github.com/smartass101/pelican/commit/e1ee4c965946d489f3e79d138ccf76a685e9581b), but that works only locally. It would work well if I could get something like `sphinx_rtd_theme.get_html_theme_path()` on RTD, but I wasn't able to find the out what the theme path is on RTD.

If CSS overriding is not possible, would it be possible to add some theme setting that would disable the current wide table handling?

**Comment by danielquinn** [comment]
If I could make on addendum to this solution:

```css
/* override table width restrictions */
@media screen and (min-width: 767px) {

  .wy-table-responsive table td {
    /* !important prevents the common CSS stylesheets from
       overriding this as on RTD they are loaded after this stylesheet */
    white-space: normal !important;
  }

  .wy-table-responsive {
    overflow: visible !important;
  }

}
```

This will enable scrolling for devices where it makes sense (phones and small tablets) and disable it for others.  I've also stripped the exception for `th` since generally those shouldn't wrap, but I leave it up to you lot to make that call.
