### ISSUE TITLE
Website bullets and menu + and - expand/collapse items broken in 1.0.0

### ISSUE THREAD

**Issue by FrightRisk** [readthedocs/sphinx_rtd_theme#1236]
## Details

* Read the Docs project URL: https://dcc-ex.com/index.html

I don't know if this happened from one of our commits, but I don't think so since we don't touch any files that would have affected this, but all our bullets everywhere are gone and our menus now look like this. The underscores should be little + signs to signify expandability:

![image](https://user-images.githubusercontent.com/37218136/133534290-10d8b094-b355-4ae9-9d2b-29e64fd30f9e.png)

The page is published using GitHub pages and not really understanding how the entire process works, I was thinking that this action script, that seems to download things from somewhere every time we publish picked up something that broke the page. When I build the page locally, it looks fine. This is the docs.yml file:

```
jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Requirements
      run: brew install sphinx-doc
        && brew install enchant
        && pip3 install sphinx-rtd-theme
        && pip3 install sphinx-sitemap
        && pip3 install sphinxcontrib-spelling
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run:  make github
        && echo 'dcc-ex.com' > docs/_build/html/CNAME
        && touch docs/_build/html/.nojekyll        
    - name: Deploy
      if: github.ref == 'refs/heads/sphinx'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
```
