### ISSUE TITLE
Bold Font of "Monaco" (OSX 10.9) in Google Chrome

### ISSUE THREAD

**Issue by wiesson** [readthedocs/sphinx_rtd_theme#127]
I have an issue with Google Chrome and the "Monaco" font! As illustrated in the following screenshot, the fallback is not used correctly in Chrome on Mac OSX 10.9.

![screenshot 2014-06-10 09 31 13](https://cloud.githubusercontent.com/assets/933231/3227341/cf449142-f079-11e3-9911-b3efa8104215.png)
Left is Google Chrome (latest), right is Safari (latest)

I have no clue wether it is a chrome problem or my mac is not correctly configured. However, "Monaco" does not have a bold-font variant. 

``` CSS
div[class^='highlight'] pre {
    white-space: pre;
    margin: 0;
    padding: 12px 12px;
    font-family: "Incosolata","Consolata","Monaco", monospace;
    font-size: 12px;
    line-height: 1.5;
    display: block;
    overflow: auto;
    color: #404040;
}
```

Safari is using some kind of monospace font, however chrome does not. Any hints or ideas? So, how about replacing "Monaco" with "Menlo" (which has both regular and bold)?
