### ISSUE TITLE
CSS Fixes

### ISSUE THREAD

**Issue by ghost** [readthedocs/sphinx_rtd_theme#136]
## Definition List

``` css
.rst-content dl dd {
    margin: 0 0 12px 24px;
}
```

looks
![staticshot_20-07-2014_20-05-47](https://cloud.githubusercontent.com/assets/1475489/3638005/657bd226-1030-11e4-9994-c00226318c01.png)

---

``` css
.rst-content dl dd {
    margin: 10px 0 12px 24px;
}
```

looks better
![staticshot_20-07-2014_20-06-09](https://cloud.githubusercontent.com/assets/1475489/3638007/7d5723dc-1030-11e4-9974-c2272b55a34e.png)
## Code Padding

```
code, .rst-content tt {
    padding: 0 5px;
}
```

looks
![staticshot_06-07-2014_11-59-12](https://cloud.githubusercontent.com/assets/1475489/3488658/f4c81946-04f8-11e4-9c4b-ff7da4b5885a.png)
![staticshot_06-07-2014_11-57-23](https://cloud.githubusercontent.com/assets/1475489/3488659/f4c848c6-04f8-11e4-858a-060886598b59.png)

---

```
code, .rst-content tt {
    padding: 2px 5px;
}
```

looks better
![staticshot_06-07-2014_11-59-59](https://cloud.githubusercontent.com/assets/1475489/3488661/0b9cfff6-04f9-11e4-951e-751a3008e0c9.png)
![staticshot_06-07-2014_11-57-52](https://cloud.githubusercontent.com/assets/1475489/3488662/0b9d8ae8-04f9-11e4-8c8a-4fe4cc0f5d29.png)
## Local Table of Contents before content

http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents

![staticshot_08-07-2014_16-19-13](https://cloud.githubusercontent.com/assets/1475489/3510049/af128502-06a2-11e4-8ea3-d7203baf6c78.png)

I think it should look like this

![staticshot_08-07-2014_16-23-01](https://cloud.githubusercontent.com/assets/1475489/3510070/00bdb6d8-06a3-11e4-974c-bc88d7e5de6c.png)

---

This happens when `.. contents::` is placed at the beginning of the file.

Here is the text an what it produces.

---

``` text
.. contents::
    :local:
    :backlinks: top

Test
====

...

Test1
-----

...

Test2
-----

...
```

![screenshot from 2014-07-11 13 27 41](https://cloud.githubusercontent.com/assets/1475489/3551381/35dd6bc0-08e6-11e4-9b71-ac8b13d19327.png)

---

``` text
Test
====

...

.. contents::
    :local:
    :backlinks: top

Test1
-----

...

Test2
-----

...

```

![staticshot_11-07-2014_13-27-09](https://cloud.githubusercontent.com/assets/1475489/3551384/47788482-08e6-11e4-9937-4c803003d6d6.png)
## &lt;ul&gt; without margin

``` css
.wy-plain-list-disc li ul,
.rst-content .section ul li ul,
.rst-content .toctree-wrapper ul li ul,
article ul li ul {
    margin-bottom: 0;
}
```

looks
![staticshot_23-07-2014_19-24-35](https://cloud.githubusercontent.com/assets/1475489/3676244/1e490d12-1286-11e4-8e25-e4c11d608328.png)

---

``` css
.wy-plain-list-disc li ul,
.rst-content .section ul li ul,
.rst-content .toctree-wrapper ul li ul,
article ul li ul {
    margin-bottom: 24px;
}

ul > li > ul {
    margin-bottom: 0 !important;
}
```

looks better
![staticshot_23-07-2014_19-25-45](https://cloud.githubusercontent.com/assets/1475489/3676248/350ddfb4-1286-11e4-912d-b1c3cfe76fbd.png)
