### ISSUE TITLE
Unable to use elements different than paragraphs in footnote bodies

### ISSUE THREAD

**Issue by joshuamzm** [readthedocs/sphinx_rtd_theme#1472]
### Problem

Footnote bodies only support plain paragraphs, as provided in https://github.com/readthedocs/sphinx_rtd_theme/pull/1381/files#diff-2ad748ac9ebc515229907afab210e3bb370986d3db3a377f052ee5048dcc5b6cR341-R343.

Trying to use different format elements breaks the grid approach, content overflows and breaks the intended layout.

Is there a reason why there is only support for the `p` tag, and not all others (`*`)? Disclaimer though, I'm not an CSS expert.

There are doc sites using the old html4 styling with lists in footnotes (e.g. [here](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id53)).

### Reproducible Project

Here's a footnote snippet with a multi-line body and a list element with two items.

```rst
  .. [#] ``action`` choices are "keep", "remove", or "adjust".

     - **"keep"** maintains existing cooling system as is, including load percentage. Using this action indicates that there are no changes to cooling at all. This action will override anything in ``adjust`` object.
     - **"remove"** indicates the existing cooling system is completely removed. New system(s) must cover 100% of load or specify ``coolLoadGapPercentage``. This action will override anything in ``adjust`` object.
```

#### Error Logs/Results

Format elements different than paragraphs overflow and break the grid layout. Here's how it shows lists in footnote bodies.

![image](https://user-images.githubusercontent.com/10285345/236965974-c8ae84bf-87ec-4ea0-a392-6bac7d7ea878.png)

#### Expected Results

For the particular case of lists, I manually added the following CSS snippet and the end result looks fine.

Extra CSS snippet:

```css
html.writer-html5 .rst-content aside.citation>ul.simple,
html.writer-html5 .rst-content aside.footnote>ul.simple,
html.writer-html5 .rst-content div.citation>ul.simple {
    grid-column-start:4;
    grid-column-end:5;
}
```

![image](https://user-images.githubusercontent.com/10285345/236965758-bbf0abbe-5e50-42b6-8d93-779acb0fec74.png)

### Environment Info

- Python Version: 3.10.8
- Sphinx Version: 7.0.0
- RTD Theme Version: 1.2.0
