### ISSUE TITLE
.sidebar class

### ISSUE THREAD

**Issue by tony** [readthedocs/sphinx_rtd_theme#16]
See `.sidebar` on http://tmuxp.readthedocs.org/en/latest/examples.html. (this is according to `/static/` css)
1. Alignment
   
   No CSS yet for `.sidebar`.
2. `height: auto !important` seems to stretch my svg image. 
   
   This is generated by [aafig](http://pythonhosted.org/sphinxcontrib-aafig/).
   
   ``` css
   .rst-content img {
     max-width: 100%;
     height: auto !important;
   }
   ```
