### ISSUE TITLE
Tables need not be scrolling

### ISSUE THREAD

**Issue by danielquinn** [readthedocs/sphinx_rtd_theme#259]
After searching through the issue queue, I see that the current wisdom on forcing `nowrap` on all table data cells is that it looks terrible on mobile, which I concede, but on a mouse-driven interface, this nowrap rule renders the content basically unreadable.

The good news though is that it need not be this way and that we can have both environments be reader-friendly, just use `@media`:

``` css
@media screen and (max-width: 767px) {
    .wy-table-responsive table td {
        white-space: nowrap;
    }
}
```

I'm not familiar with SASS, but there must be a way to implement these sorts of rules with it, yes?  This would make `td` cells scrollable on small devices, and readable on larger ones.  I don't see the downside.
