### ISSUE TITLE
Enumerated lists with mixed numbering broken

### ISSUE THREAD

**Issue by jantman** [readthedocs/sphinx_rtd_theme#718]
### Problem

Using 0.4.2, nested enumerated lists in HTML output use the same number or letter as the parent list instead of using the defined or default nested list numbering.

I believe this is likely related to #484, but has nothing to do with bullet (non-enumerated) lists.

### Reproducible Project

```rst
A. Foo

   1) Blam
   #) Blarg

      i. Something

   #) Quux

#. Bar
#. Baz
```

#### Error Logs/Results

The result with ``html_theme = "sphinx_rtd_theme"`` is incorrect numbering. The visible output in a browser is:

![rtd](https://user-images.githubusercontent.com/273454/51982050-ee9a5f00-2462-11e9-83e1-ed53c2b3abf3.png)

#### Expected Results

The expected result can be achieved using the alabaster theme (``html_theme = 'alabaster'``):

![alabaster](https://user-images.githubusercontent.com/273454/51982052-f1954f80-2462-11e9-9a37-2892217bfe03.png)

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 1.8.3
- RTD Theme Version: 0.4.2

**Comment by jantman** [comment]
For this particular (exact) example, I was able to fix the issue with the following theme CSS override:

```css
.rst-content ol.arabic > li { list-style-type: decimal !important }
.rst-content ol > li > ol { margin-bottom:0 !important }
.rst-content ol.lowerroman > li { list-style-type: lower-roman !important }
```
