### ISSUE TITLE
Nav panel CSS problem: deeply nested items are rendered incorrectly

### ISSUE THREAD

**Issue by pavel-kirienko** [readthedocs/sphinx_rtd_theme#776]
### Problem

The nav sidebar is rendered incorrectly at deep levels of nesting. The issue can be reproduced by defining a document structure with at least 5 levels of nesting and increasing the TOC depth limit appropriately.

The culprit seems to be located around here:

https://github.com/readthedocs/sphinx_rtd_theme/blob/2c15fde411c3d2a85acf710ba661312dc8596b11/sass/_theme_layout.sass#L132-L134

For now, I use the following dirty hack which kinda hides the problem:

```css
.wy-menu-vertical li.toctree-l3 li.toctree-l4 li.toctree-l5                                                         > a { padding-left:  7em; background: #ddd; }
.wy-menu-vertical li.toctree-l3 li.toctree-l4 li.toctree-l5 li.toctree-l6                                           > a { padding-left:  8em; background: #ccc; }
.wy-menu-vertical li.toctree-l3 li.toctree-l4 li.toctree-l5 li.toctree-l6 li.toctree-l7                             > a { padding-left:  9em; background: #bbb; }
.wy-menu-vertical li.toctree-l3 li.toctree-l4 li.toctree-l5 li.toctree-l6 li.toctree-l7 li.toctree-l8               > a { padding-left: 10em; background: #aaa; }
.wy-menu-vertical li.toctree-l3 li.toctree-l4 li.toctree-l5 li.toctree-l6 li.toctree-l7 li.toctree-l8 li.toctree-l9 > a { padding-left: 11em; background: #999; }
```

### Environment Info

- Python Version: 3.7
- Sphinx Version: 2.1
- RTD Theme Version: 0.4.3
