### ISSUE TITLE
Fix use of code:: console in docs

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#794]
Noticed in #787 the STDOUT output of `code:: console` is not super legible. For our docs, there are two solutions:

* Revert to `code:: bash` -- there is no console output in our docs to differentiate from input
* Add the `$` prefix -- in other RTD docs, we've moved away from prefixing command line operations to make copy paste easier

I suppose I lean slightly towards using `code:: bash` if there aren't strong reasons for `code:: console`

**Comment by jessetan** [comment]
The `$` prompt indicator can be made unselectable and therefore uncopyable with the following CSS.

```css
/* Do not allow selection of code block prompts */
div.highlight .gp {
    user-select: none;
    pointer-events: none;
}
```

If the presence of `$` is confusing, using `bash` is OK
