### ISSUE TITLE
Footnotes, Citations and Glossary rendering wrong

### ISSUE THREAD

**Issue by kjshen** [readthedocs/sphinx_rtd_theme#942]
### Problem

I have the same problem as described in #741:

Footnotes, Citations and Glossary are not rendered as shown [here](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#references).

### Reproducible Project

I've created a new project using sphinx-quickstart and changed the html_theme to 'sphinx_rtd_theme'.

```rst
References
==========

Footnotes
---------

.. [1] A footnote contains body elements, consistently indented by at
   least 3 spaces.

   This is the footnote's second paragraph.

.. [#label] Footnotes may be numbered, either manually (as in [1]_) or
   automatically using a "#"-prefixed label.  This footnote has a
   label so it can be referred to from multiple places, both as a
   footnote reference ([#label]_) and as a hyperlink reference
   (label_).

.. [#] This footnote is numbered automatically and anonymously using a
   label of "#" only.

.. [*] Footnotes may also use symbols, specified with a "*" label.
   Here's a reference to the next footnote: [*]_.

.. [*] This footnote shows the next symbol in the sequence.

.. [4] Here's an unreferenced footnote, with a reference to a
   nonexistent footnote: [5]_.

Citations
---------

.. [11] This is the citation I made, let's make this extremely long so that we can tell that it doesn't follow the normal responsive table stuff.

.. [12] This citation has some ``code blocks`` in it, maybe some **bold** and
       *italics* too. Heck, lets put a link to a meta citation [13]_ too.

.. [13] This citation will have two backlinks.


Here's a reference to the above, [12]_, and a [nonexistent]_ citation.

Here is another type of citation: `citation`

Glossary
--------

This is a glossary with definition terms for thing like :term:`Writing`:

.. glossary::
  
  Documentation
     Provides users with the knowledge they need to use something.

  Reading
     The process of taking information into ones mind through the use of eyes.

  Writing
     The process of putting thoughts into a medium for other people to :term:`read <Reading>`.
```

#### Results

![grafik](https://user-images.githubusercontent.com/45091615/83815485-97dd0f00-a6c0-11ea-8162-c90a3dae14d9.png)

#### Expected Results

![grafik](https://user-images.githubusercontent.com/45091615/83815518-a88d8500-a6c0-11ea-9d60-b7822279727d.png)

### Environment Info

- Python Version: 3.8.1
- Sphinx Version: 3.0.4
- RTD Theme Version: 0.4.3

**Comment by agjohnson** [comment]
Closing as a duplicate, this is already resolved in master and available on the 0.5.0rc2 release.

**Comment by kjshen** [comment]
Hi, thank you for the reply.

As I mentioned in my post, I found #741 and thereby #838, which I assume are the duplicates. Could someone direct me as to how I should've known that this issue was already resolved in a version that was not released yet?

After looking at the dates of those issues I had already assumed that I encountered a new occurence of this issue.

**Comment by idnsunset** [comment]
> Closing as a duplicate, this is already resolved in master and available on the 0.5.0rc2 release.

#838 fixed footnotes and glossary, but not citation. The code in `theme.css` shown as below doesn't filter out `.citation`.

```css
html.writer-html4 .rst-content dl:not(.docutils)>dt,html.writer-html5 .rst-content dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.glossary):not(.simple)>dt {
    display: table;
    margin: 6px 0;
    font-size: 90%;
    line-height: normal;
    background: #e7f2fa;
    color: #2980b9;
    border-top: 3px solid #6ab0de;
    padding: 6px;
    position: relative
}
```
The style applied to footnotes should be applied to citation as well.
