### ISSUE TITLE
Rendering of Definition List/Option List/Field List

### ISSUE THREAD

**Issue by bearsh** [readthedocs/sphinx_rtd_theme#979]
### Problem

Definition List/Option List/Field List are rendered differently on ReadTheDocs than in a local build. See attached screenshots:

on https://sphinx-rtd-theme.readthedocs.io/en/0.5.0/
![2020-07-13 15 51 18 sphinx-rtd-theme readthedocs io 1deb0b91adf1](https://user-images.githubusercontent.com/1089356/87312969-96093580-c521-11ea-8b40-dfcbb1fb34fb.png)

local build:
![2020-07-13 15 51 29  b0340eff0d13](https://user-images.githubusercontent.com/1089356/87313066-b20cd700-c521-11ea-85ed-3d063de3bcaf.png)

### Environment Info

- Python Version: 3.6.8
- Sphinx Version: 3.1.2
- RTD Theme Version: 0.5.0

**Comment by jobec** [comment]
Same here.
The CSS code seems to have disappeared completely.

**Comment by jobec** [comment]
It seems to have disappeared in commit ff594d23ff16b52f3a2d626e7c8b295f550e0de1 by @agjohnson

**Comment by agjohnson** [comment]
Oops, I see the issue. Nothing disappeared, but the versioned docs are being built with `sphinx_rtd_theme==0.4.3` still. The last PR build looks fine:
https://sphinx-rtd-theme--981.org.readthedocs.build/en/981/demo/lists_tables.html#definition-lists

PR builds use the local version of the theme, not a pinned version of the PyPI theme. I'd prefer if the versioned docs are built using the local theme as well -- that is, 0.5.0 docs use the local 0.5.0 of the theme -- but I think there were some objections to that previously.

**Comment by bearsh** [comment]
@agjohnson thanks for the info.

so the design change was intended. that's good to know although I'm not 100% happy with it. I like it for the field list but not for the definition list. for the option list I'm uncertain... a little bit off topic but is the a easy way to revert it locally (css override) for the definition list but leave it for the field list?

**Comment by jobec** [comment]
To bring back the definition list style, I added this CSS via a custom stylesheet file:

```css
.rst-content dl:not(.docutils) dt:first-child {
  margin-top: 0;
}
.rst-content dl:not(.docutils) dt {
  display: table;
  margin: 6px 0;
  font-size: 90%;
  line-height: normal;
  background: #e7f2fa;
  color: #2980B9;
  border-top: solid 3px #6ab0de;
  padding: 6px;
  position: relative;
}
```

@agjohnson , are you 100% sure the removal of those styles was intentional, rather than by mistake?
