### ISSUE TITLE
Feature request: Hide/autohide sidebar

### ISSUE THREAD

**Issue by klieret** [readthedocs/sphinx_rtd_theme#987]
When writing tutorials in sphinx, we usually ask students to have the tutorial and the terminal side-by-side on their screen. However, the sidebar in sphinx is quite large, so it would be really useful if it would auto hide or could be hidden by the press of a button.

I know it's possible to hide it using something like

```css


.wy-nav-side {
  display: none;
}

.wy-nav-content-wrap {
  margin-left: 0;
}
```

but it would be really nice to make have the option of toggling it.
