### ISSUE TITLE
Inconsistent vertical spacing in nested lists

### ISSUE THREAD

**Issue by klieret** [readthedocs/sphinx_rtd_theme#996]
### Problem

The vertical spacing is inconsistent in nested list. 

### Reproducible Project

From the RTD theme documentation itself:

```rst

- I kept saying that, "deeper down the rabbit hole". `yahoo <http://www.yahoo.com>`_

  - I cackle at night `yahoo <http://www.yahoo.com>`_.
- I'm so lonely here in GZ ``guangzhou``
```

Note: Adding additional blank lines doesn't help 

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/13602468/92327828-aab70500-f05c-11ea-80b3-a464159b9b62.png)

#### Expected Results

Either

* No space _before_ "I cackle at night yahoo"
* No space _after_ "I cackle at night yahoo"

**Comment by chausner-audeering** [comment]
I am working around this layout issue with some custom CSS overrides:

```css
.wy-plain-list-disc li ul,
.rst-content .section ul li ul,
.rst-content .toctree-wrapper ul li ul,
article ul li ul {
 margin-bottom:12px;
}
```

Tested for version 0.4.3.
